project_id = "ectjkhvieobbinepncle"

[functions.interview-feedback]
verify_jwt = true

[functions.generate-questions]
verify_jwt = true

[functions.essay-check]
verify_jwt = true

[functions.expand-questions]
verify_jwt = true

[functions.send-verification-code]
verify_jwt = false

[functions.verify-code]
verify_jwt = false

[functions.send-reset-email]
verify_jwt = false
